name: Build and Deploy Next.js

on:
  push:
    branches:
      - main  # Cambia 'main' por el nombre de tu rama principal

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '13'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  deploy:
    needs: build
    runs-on: windows-latest
    if: github.ref == 'refs/heads/main'  # Cambia 'main' por tu rama principal

    steps:
      - name: Deploy to hosting service
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./out  
          github_token: ${{ secrets.GITHUB_TOKEN }}
